name: Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: read-all

jobs:
  Build-Documentation:
    runs-on: [self-hosted, A100]
    timeout-minutes: 30

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PAT }}
          fetch-depth: 0

      - name: Clear docs
        run: |
          rm -r /tmp/triton-docs
        continue-on-error: true

      - name: Install dependent packages
        run: |
          sudo pip3 install tabulate cmake sphinx matplotlib myst_parser sphinx-rtd-theme pandas pytest sphinx-gallery sphinx-multiversion

      #- name: Fetch dependent branches
      #  run: |
      #    git fetch origin main:main

      - name: Build docs
        run: |
          cd docs
          export PATH=$(python3 -c "import cmake; print(cmake.CMAKE_BIN_DIR)"):$PATH
          sudo python3 -m sphinx . _build/html/main

      - name: Update docs
        run: |
          export TMP_DOCS_PATH=/tmp/triton-docs/
          sudo mkdir $TMP_DOCS_PATH
          sudo mv docs/_build/html/* $TMP_DOCS_PATH
          sudo git checkout gh-pages
          sudo cp -r CNAME $TMP_DOCS_PATH
          sudo cp -r index.html $TMP_DOCS_PATH
          sudo cp -r .nojekyll $TMP_DOCS_PATH
          sudo rm -r *
          sudo cp -r $TMP_DOCS_PATH/* .
          sudo rm -r $TMP_DOCS_PATH
          sudo git add .
          sudo git config --global user.email "N/A"
          sudo git config --global user.name "gh-actions-bot"
          sudo git commit -am "[GH-PAGES] Updated website"

      - name: Publish docs
        run: |
          sudo git push origin gh-pages
