name: Documentation
on:
  workflow_dispatch:
  schedule:    
    - cron: "0 0 * * *"

jobs:

  Build-Documentation:
    
    runs-on: self-hosted

    steps:


      - name: Checkout gh-pages
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'

      - name: Checkout branch
        uses: actions/checkout@v1

      # - name: Install Triton
      #   run: |
      #     alias python='python3'
      #     cd python
      #     pip3 install -e '.[tutorials]'

      - name: Build docs
        run: |
          git fetch origin master:master
          cd docs
          sphinx-multiversion . _build/html/

      - name: Publish docs
        run: |
          git branch
          # update docs
          rm -r /tmp/triton-docs; 
          mkdir /tmp/triton-docs;
          mv docs/_build/html/* /tmp/triton-docs/
          git checkout gh-pages
          cp -r CNAME /tmp/triton-docs/
          cp -r .nojekyll /tmp/triton-docs/
          cp -r update-website.sh /tmp/triton-docs/
          rm -r *
          cp -r /tmp/triton-docs/* .
          ln -s master docs
          git add .
          git commit -am "[GH-PAGES] Updated website"
          # publish docs
          eval `ssh-agent -s`
          DISPLAY=:0 SSH_ASKPASS=~/.ssh/give_pass.sh ssh-add ${{ secrets.SSH_KEY }} <<< ${{ secrets.SSH_PASS }}
          git remote set-url origin git@github.com:openai/triton.git
          git push
